# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootwearStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('OXF', 'Oxford'), ('DRB', 'Derby'), ('BRG', 'Brogue'), ('MNK', 'Monk'), ('BML', 'Balmoral')], max_length=3, verbose_name='style')),
                ('footwear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='shop.Footwear', verbose_name='footwear')),
            ],
        ),
        migrations.AddField(
            model_name='hat',
            name='brands',
            field=models.ManyToManyField(related_name='new_hats', to='shop.Brand', verbose_name='brands'),
        ),
        migrations.AlterField(
            model_name='hat',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats',
                                    to='shop.Brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='hat',
            name='colour',
            field=models.TextField(blank=True, default='', verbose_name='colour'),
        ),
        migrations.AlterField(
            model_name='hat',
            name='style',
            field=models.CharField(choices=[('FED', 'Fedora'), ('TOP', 'Top Hat'), ('TBY', 'Trilby'), ('PNM', 'Panama'), ('FEZ', 'Fez'), ('CAP', 'Cap')], max_length=3, verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='style',
            field=models.CharField(blank=True,
                                   choices=[('OXF', 'Oxford'), ('DRB', 'Derby'), ('BRG', 'Brogue'), ('MNK', 'Monk'),
                                            ('BML', 'Balmoral')], default='', max_length=3, verbose_name='style'),
        ),

    ]
